### ISSUE TITLE
Allow the step size `ds` to be passed as a function

### ISSUE THREAD

**Issue by cgt3** [cgt3/PathIntersections.jl#10]
Allow the step size ds to itself be a function of s. For example,  `ds[c]` or `ds` would become `ds[c](s)`/`ds(s)`. This would be an alternative to adaptive stepping and would be very beneficial for compound curves that may need different step sizes over each of their segments.

**Comment by jlchan** [comment]
If we have different compound curves, it might also make sense to be able to pass in different `ds(s)` for each curve.
